image: python:3.8-slim

stages:
    - build
    - test
    - artifact

build:
    stage: build
    script:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - python setup.py sdist bdist_wheel
        - pip install dist/*
    artifacts:
        paths:
            - dist/*.whl
        expire_in: 1 week
    tags:
        - docker

test:
    stage: test
    allow_failure: true
    script:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - python setup.py test
    tags:
        - docker

publish:
    stage: artifact
    variables:
        TWINE_USERNAME: $TWINE_USERNAME
        TWINE_PASSWORD: $TWINE_PASSWORD
    script:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - python setup.py sdist bdist_wheel
        - pip install -U twine
        - twine upload --verbose dist/*
    artifacts:
        paths:
            - dist/*.whl
    #    expire_in: 1 month
    tags:
        - docker
    only:
        - tags
        - /^v.*$/
